# Generated by Django 5.0.14 on 2025-12-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio or tagline for the user profile', null=True),
        ),
    ]
