# Generated by Django 5.0.14 on 2025-12-14 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='', help_text='City/Area (e.g. Ikeja)', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='duration',
            field=models.PositiveIntegerField(default=1, help_text='Rental duration in years'),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(default='', help_text='State (e.g. Lagos)', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(help_text='Full Address', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Rent amount in Naira', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
