# Generated by Django 5.0.14 on 2025-12-18 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_propertyvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='num_toilets',
            field=models.PositiveIntegerField(default=0, help_text='Number of toilets', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='num_bathrooms',
            field=models.PositiveIntegerField(help_text='Number of bathrooms', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
