# Generated by Django 5.0.14 on 2025-12-19 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_num_toilets_alter_property_num_bathrooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='duration',
        ),
    ]
