
export const NIGERIAN_STATES = [
    { state: "Abia", cities: ["Aba", "Umuahia"] },
    { state: "Adamawa", cities: ["Yola", "Mubi"] },
    { state: "Akwa Ibom", cities: ["Uyo", "Eket", "Ikot Ekpene"] },
    { state: "Anambra", cities: ["Awka", "Onitsha", "Nnewi"] },
    { state: "Bauchi", cities: ["Bauchi", "Azare"] },
    { state: "Bayelsa", cities: ["Yenagoa", "Brass"] },
    { state: "Benue", cities: ["Makurdi", "Gboko", "Otukpo"] },
    { state: "Borno", cities: ["Maiduguri", "Jere"] },
    { state: "Cross River", cities: ["Calabar", "Ikom", "Ogoja"] },
    { state: "Delta", cities: ["Asaba", "Warri", "Ughelli", "Sapele"] },
    { state: "Ebonyi", cities: ["Abakaliki", "Afikpo"] },
    { state: "Edo", cities: ["Benin City", "Auchi", "Ekpoma"] },
    { state: "Ekiti", cities: ["Ado Ekiti", "Ikere"] },
    { state: "Enugu", cities: ["Enugu", "Nsukka", "Awgu"] },
    { state: "Gombe", cities: ["Gombe", "Kaltungo"] },
    { state: "Imo", cities: ["Owerri", "Okigwe", "Orlu"] },
    { state: "Jigawa", cities: ["Dutse", "Hadejia"] },
    { state: "Kaduna", cities: ["Kaduna", "Zaria", "Kafanchan"] },
    { state: "Kano", cities: ["Kano", "Wudil"] },
    { state: "Katsina", cities: ["Katsina", "Daura"] },
    { state: "Kebbi", cities: ["Birnin Kebbi", "Argungu"] },
    { state: "Kogi", cities: ["Lokoja", "Okene", "Idah"] },
    { state: "Kwara", cities: ["Ilorin", "Offa"] },
    { state: "Lagos", cities: ["Ikeja", "Lekki", "Victoria Island", "Ikoyi", "Yaba", "Surulere", "Ajah", "Ikorodu", "Epe", "Badagry"] },
    { state: "Nasarawa", cities: ["Lafia", "Keffi", "Karu"] },
    { state: "Niger", cities: ["Minna", "Suleja", "Bida"] },
    { state: "Ogun", cities: ["Abeokuta", "Ijebu Ode", "Sango Ota", "Sagamu"] },
    { state: "Ondo", cities: ["Akure", "Ondo City", "Owo"] },
    { state: "Osun", cities: ["Osogbo", "Ile-Ife", "Ede"] },
    { state: "Oyo", cities: ["Ibadan", "Ogbomosho", "Oyo"] },
    { state: "Plateau", cities: ["Jos", "Bukuru"] },
    { state: "Rivers", cities: ["Port Harcourt", "Obio-Akpor", "Bonny", "Eleme"] },
    { state: "Sokoto", cities: ["Sokoto", "Tambuwal"] },
    { state: "Taraba", cities: ["Jalingo", "Wukari"] },
    { state: "Yobe", cities: ["Damaturu", "Potiskum"] },
    { state: "Zamfara", cities: ["Gusau", "Kaura Namoda"] },
    { state: "Abuja (FCT)", cities: ["Garki", "Wuse", "Maitama", "Asokoro", "Gwarinpa", "Kubwa", "Lugbe"] },
];
