# Generated by Django 5.0.14 on 2025-12-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyTypeHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('APARTMENT', 'Apartment'), ('HOUSE', 'House'), ('CONDO', 'Condo'), ('TOWNHOUSE', 'Townhouse')], help_text='Property type', max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Brief description')),
                ('image_url', models.URLField(blank=True, help_text='Optional image URL', max_length=500)),
                ('content', models.TextField(help_text='Detailed content (supports HTML)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property Type Help',
                'verbose_name_plural': 'Property Type Help Pages',
                'ordering': ['order', 'property_type'],
            },
        ),
    ]
